### PR TITLE
Fixes and missing operator implementations for btorsim

### LINKED ISSUE #22: btorsim: `BTOR2_tag_iff` not marked as implemented
Btorsim is missing an implementation of the `iff` operation.

### LINKED ISSUE #23: btorsim: missing implementation for `BTOR2_tag_rol`, `BTOR2_tag_ror`, and `BTOR2_tag_smod`
Btorsim is missing an implementation of the rotation operations `rol`, `ror`, and `smod`

### LINKED ISSUE #24: btorsim: incorrect implementation for `BTOR2_tag_sra`
Btorsim's implementation for `sra` (shift arithmetic right) is wrong for negative inputs. It doesn't correctly check the sign bit of the left operand to determine whether to shift in zeros or ones.

Testcase:

```
;; -----------------------------------------------------------------------------
;; manually written btor file for testing binary operators
;; -----------------------------------------------------------------------------
1 sort bitvec 1
2 sort bitvec 8
;; -----------------------------------------------------------------------------
;; arithmetic shift right negative
;; -----------------------------------------------------------------------------
3 constd 2 4
4 const 2 10110110
5 const 2 11111011
6 sra 2 4 3
7 eq 1 5 6
8 bad 7 sra-negative
```

Witness:

```
#0
@0
.
```

### PR DESCRIPTION
**Pull request by Ferdi265**
This PR implements the missing operations `iff`, `rol`, `ror`, and `smod` in btorsim and fixes the implementation for `sra`.

Btorsim already has an implementation for iff, but it wasn't marked as implemented.

Implement rol and ror by delegating to sll and srl and or-ing the results together.

Smod implementation taken from boolector ([src/btorexp.c:1528](https://github.com/Boolector/boolector/blob/6603ed7b8d401f9bf387f32c702e3e938c50924d/src/btorexp.c#L1528))

The previous sra implementation wasn't working for negative inputs. The implementation was extracting the wrong sign bit (from b instead of a) and also accidently forgot to use it in the conditional, and used not_a instead.

This fixes #22, fixes #23, and fixes #24

### CODE REVIEW

**Comment by Ferdi265** [comment]
sorry for the many edits to this PR yesterday; should be ready for review now

File: src/btorsim/btorsimbv.c [hunk 1]
```diff
@@ -2001,6 +2033,70 @@ btorsim_bv_srem (const BtorSimBitVector *a, const BtorSimBitVector *b)
...
+                                   : btorsim_bv_copy(b);
+
+    neg_urem = btorsim_bv_neg (urem);
+    add_urem = btorsim_bv_add(urem, add);
+    add_neg_urem = btorsim_bv_add(neg_urem, add);
+
+    res =  a_positive &&  b_positive ? btorsim_bv_copy(urem)
+        : !a_positive &&  b_positive ? btorsim_bv_copy(add_neg_urem)
+        :  a_positive && !b_positive ? btorsim_bv_copy(add_urem)
+                                     : btorsim_bv_copy(neg_urem);
```
Comment (mpreiner) [inline src/btorsim/btorsimbv.c:2080]: You could do the case split explicitly and only compute neg_urem, add_urem, and add_neg_urem if needed.

**Comment by mpreiner** [comment]
@Ferdi265 Thanks a lot for the additions/fixes! Sorry that it took so long for reviewing the PR.

File: src/btorsim/btorsimbv.c (hunk 1 above)
Comment (Ferdi265) [reply src/btorsim/btorsimbv.c:2080]: will do

Comment (Ferdi265) [reply src/btorsim/btorsimbv.c:2080]: I just noticed that this seems to make the memory management and control flow a lot more complicated:

- `add` is needed for `!a_positive && b_positive` and `a_positive && !b_positive`
- `neg_urem` is needed for `!a_positive && b_positive` and `!a_positive && !b_positive` (the else case)
- `add_neg_urem` is only needed for `!a_positive && b_positive`

This is not cleanly separable without either doing things twice or checking for the cases multiple times. Especially since all bitvectors need to be free'd at the end, and only bitvectors that were initialized are allowed to be free'd.

Also, since the codebase seems to go out of its way to define all variables up top, it would make it difficult to see at a glance why some specific bitvectors aren't free'd in the big block at the end of the function while some others are.

The same pattern of computing `neg_urem` even when it isn't needed is also present in the implementation of `srem` and something similar also happens with `sdiv`.

What I can do is do the computation of `add_neg_urem` and `add_urem` inline and drop the extra variables for `add_neg_urem` and `add_urem`, because that doesn't complicate the control flow or liveness of the variables.
